name: testing

on: push

jobs:
  build:
#    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
#        if: contains(github.event.comment.html_url, '/deploy')
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm test

  deploy:
    needs: test

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: staging
      url: ${{ steps.deployment.outputs.page_url }} # output of the deployment in steps

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: configure github pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next # allows the nextjs website to be build
      - run: npm install
      - run: npm run build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
